template_detector_depth:
  ros__parameters:
    # ==================== 相机配置 ====================
    # RGB相机索引（通道4）
    rgb_camera_index: 4
    
    # 深度相机索引（通道2）
    depth_camera_index: 2
    
    # 是否使用RealSense相机（如果是RealSense，RGB和深度在同一设备）
    # true: 使用RealSense SDK获取对齐的RGB和深度
    # false: 使用两个独立的相机（通道2和4）
    use_realsense: false
    
    # ==================== 模板检测参数 ====================
    # 模板图片路径（包含1.png到15.png）
    template_base_path: "/home/haowen/BUAARobertTeam/abu robocon 2026 map/贴图/R2 KFS图案"
    
    # 蓝色HSV范围
    lower_blue: [90, 50, 50]
    upper_blue: [130, 255, 255]
    
    # 最小轮廓面积（像素）
    min_contour_area: 1000
    
    # 矩形检测阈值
    angle_thresh: 15        # 角度阈值（度）
    aspect_thresh: 0.3      # 纵横比阈值
    overlap_thresh: 50      # 重叠阈值（像素）
    
    # ==================== 相机内参 ====================
    # 焦距和主点坐标
    fx: 608.692
    fy: 608.622
    cx: 328.773
    cy: 243.008
    
    # ==================== 相机外参 (4x4矩阵) ====================
    # 从世界坐标系到相机坐标系的变换矩阵（行优先）
    # 当前设置：相机位于世界坐标系的(100, 100, 100)mm位置，无旋转
    # 格式: [R11, R12, R13, tx, R21, R22, R23, ty, R31, R32, R33, tz, 0, 0, 0, 1]
    extrinsic_matrix: [
      1.0, 0.0, 0.0, 100.0,   # 第1行
      0.0, 1.0, 0.0, 100.0,   # 第2行
      0.0, 0.0, 1.0, 100.0,   # 第3行
      0.0, 0.0, 0.0, 1.0      # 第4行
    ]
    
    # ==================== 可视化参数 ====================
    # 启用可视化窗口
    enable_visualization: true
    
    # 显示深度图
    show_depth_map: true
    
    # 显示FPS
    show_fps: true